[package]
name = "progredient"
version = "1.0.0"
edition = "2021"
license = "MIT"
description = "A program to render text progress bars."
repository = "https://github.com/fabjan/progredient"
keywords = ["cli", "scripts", "terminal"]

[dependencies]
progressing = "3.0.2"
